### ISSUE TITLE
Improve PAD normalization script

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-importer#19]
This is an open-ended issue that will be chopped up into more discrete tasks after we complete the documentation in #16

**Comment by allthesignals** [comment]
Questions for Steve: 
 - [ ] What do we do with rows that have  non-blank`addrtype` values?
 - [ ] How should blank `addrtype` values be handled?

**Comment by chriswhong** [comment]
Closed, added #9, #10, #11, #12, #13, #14, #15
