### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [NYCPlanning/labs-geosearch-pad-importer#26]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project uses curl, which [will not follow redirects by default](https://davidwalsh.name/curl-follow-redirects).

Would it please be possible to update all files from http://planet.openstreetmap.org to  http**s**://planet.openstreetmap.org before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https?

**Comment by grischard** [comment]
Yes, [my search was pretty basic](https://github.com/NYCPlanning/labs-geosearch-pad-importer/search?utf8=%E2%9C%93&q=%22http%3A%2F%2Fplanet.openstreetmap.org%22+curl&type=).

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #6](https://github.com/NYCPlanning/labs-geosearch-docker/issues/6) via [**ZenHub**](https://www.zenhub.com/)
