### ISSUE TITLE
Handle Capitalization

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-importer#9]
Raw data in PAD contains street names in all capitals.  We should explore ways to smartly modify case during import so that the results are prettier.

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #11](https://github.com/NYCPlanning/labs-geosearch-docker/issues/11) via [**ZenHub**](https://www.zenhub.com/)
